{% set name = "rich-argparse" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rich_argparse-{{ version }}.tar.gz
  sha256: c530aad416d83fdee28446097e51daab4b9efb0d1c7d2407107f4b0681daaff8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.11.0
    - pip
  run:
    - python >=3.7
    - rich >=11.0.0

test:
  imports:
    - rich_argparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hamdanal/rich-argparse
  summary: Rich help formatters for argparse and optparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/hamdanal/rich-argparse

extra:
  recipe-maintainers:
    - xylar
