{% set name = "rich-argparse" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rich_argparse-{{ version }}.tar.gz
  sha256: 092083c30da186f25bcdff8b1d47fdfb571288510fb051e0488a72cc3128de13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.11.0
    - pip
  run:
    - python >={{ python_min }}
    - rich >=11.0.0

test:
  imports:
    - rich_argparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hamdanal/rich-argparse
  summary: Rich help formatters for argparse and optparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/hamdanal/rich-argparse

extra:
  recipe-maintainers:
    - xylar
